# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6928df8be00651a17b2060210736649b73fedba9a102ce3fa2a98f65efdf729819431a6b7e087aed072b4e1ee477f6f713238bdf87fe96ab947fd3e559450506

test:
  secret_key_base: 31379694a12665d19c7f7cf822ff02c38f8698406f8d208193f7db2c66d0239279e8bf0ebe178dcc2d1ca1fa4776b2ddd4023c6eff833f5e04614ed97e1ec479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
